### PR TITLE
add gitignore and remove .DS_Store file and other files not needed to be tracked

### PR DESCRIPTION
**Pull request by robbyoconnor**
This adds a gitignore and removes files that aren't needed to be tracked in git.

### CODE REVIEW

**Comment by samuelmale** [comment]
Thanks @robbyoconnor

**Comment by dkayiwa** [comment]
Nice catch @robbyoconnor 👍

**Comment by robbyoconnor** [comment]
Fun fact: `git add . ; git commit --amend -m "..."` effectively does a rebase/squash for you :)

**Comment by dkayiwa** [comment]
oh, interesting! 😊

**Comment by robbyoconnor** [comment]
Also issues need to be turned off on this repo.

**Comment by dkayiwa** [comment]
Thanks for the reminder. I have just turned it off.

**Pull request merged**
